---
title: Chorley Model Club
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  indexes:
    title: indexes
    output: false
email: egnshane@gmail.com
url: http://chorleymac.co.uk/
description: Chorley Model Club - Friendly, local, multi discipline radio controlled
  model flying club located in the Yarrow Valley Park Chorley. New members are always
  welcome.
tag_line: Friendly, local, multi discipline model flying club
meta_author: Egan Shane
google_verify: 
bing_verify: 
contact: static
disqus_shortname: myshortname
color:
  primary: 66d9ff
  primary-rgb: '24,288,156'
  secondary: 2c3e50
  secondary-dark: 233140
footer:
  copyright: Chorley Model Club
  location: Location
  social: Around the Web
  credits: Credits
social:
- title: file-text-o
  url: http://chorleysrms.freeforums.net/
address:
- line: Lower Burgh Meadow
- line: Chorley, PR7 3QN
credits: Thanks for all the efforts of our club members
markdown: kramdown
permalink: pretty
