# Site settings
title: Chorley Model Club
email: egnshane@gmail.com
url: http://chorleymac.co.uk/
description: "Chorley Model Club - Friendly, local, multi discipline model flying club. New members are always welcome."
skills: "Friendly, local, multi discipline model flying club"
meta_author: Egan Shane

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Chorley Model Club
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: file-text-o
    url: http://chorleymodelaircraftclub.freeforums.org/index.php
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Lower Burgh Meadow
  - line: Chorley, PR7 3QN

# Credits content
credits: 'Thanks for all the efforts of our club members'

# Build settings
markdown: kramdown
permalink: pretty
